version: '3'

services:
  json-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
